import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const courierPrimeRegular = localFont({
  src: "./fonts/Courier_Prime/CourierPrime-Regular.ttf",
  variable: "--font-courier-prime-regular"
})

const IBMPlexMonoRegular = localFont({
  src: "./fonts/IBM_Plex_Mono/IBMPlexMono-Regular.ttf",
  variable: "--font-IBM-plex-mono-regular"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${ courierPrimeRegular.variable } ${ IBMPlexMonoRegular.variable }`}>
        {children}
      </body>
    </html>
  );
}
